name = "sodium"
version = "0.2.0"
license = "MIT"
author = "Andre Smit"
maintainer = "freevryheid@gmail.com"
copyright = "Copyright 2022, Andre Smit"
[build]
link = ["sodium"]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
